apiVersion: networkaddonsoperator.network.kubevirt.io/v1alpha1
kind: NetworkAddonsConfig
metadata:
  name: cluster
spec:
  multus:
    delegates: |
      [{
        "type": "flannel",
        "name": "flannel.1",
        "delegate": {
          "isDefaultGateway": true
        }
      }]
  linuxBridge: {}
