apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: cluster-network-addons-operator.v0.0.0
  namespace: placeholder
  annotations:
    capabilities: "Full Lifecycle"
    categories: "Network/Networking"
    alm-examples: |
      [
        {
          "apiVersion":"networkaddonsoperator.network.kubevirt.io/v1alpha1",
          "kind":"NetworkAddonsConfig",
          "metadata": {
            "name":"cluster",
          },
          "spec": {
            "multus":{},
            "linuxBridge":{},
            "sriov":{},
            "kubeMacPool": {
              "startPoolRange": "02:00:00:00:00:00",
              "endPoolRange": "FD:FF:FF:FF:FF:FF",
            }
            "imagePullPolicy": "Always",
          }
        }
      ]
    description: Additional networking components for Kubernetes
spec:
  displayName: Cluster Network Addons
  description: Deploy additional networking components for Kubernetes
  keywords:
    - KubeVirt
    - Virtualization
    - Networking
    - Multus
    - CNI
    - macpool
    - SR-IOV
    - Bridge
  version: 0.0.0
  maturity: alpha

  maintainers:
    - name: KubeVirt project
      email: kubevirt-dev@googlegroups.com
  provider:
    name: KubeVirt project
  links:
    - name: KubeVirt
      url: https://kubevirt.io
    - name: Source Code
      url: https://github.com/kubevirt/cluster-network-addons-operator
  icon: []
  labels:
    alm-owner-kubevirt: cluster-network-addons
    operated-by: cluster-network-addons
  selector:
    matchLabels:
      alm-owner-kubevirt: cluster-network-addons
      operated-by: cluster-network-addons
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: true
    - type: MultiNamespace
      supported: true
    - type: AllNamespaces
      supported: true
  install:
    strategy: deployment
    spec:
      clusterPermissions:
        - serviceAccountName: cluster-network-addons-operator
          rules:
            - apiGroups:
              - ""
              resources:
              - events
              verbs:
              - create
              - update
              - patch
            - apiGroups:
              - ""
              resources:
              - persistentvolumeclaims
              verbs:
              - get
              - list
              - watch
              - create
              - update
              - patch
              - delete
            - apiGroups:
              - ""
              resources:
              - persistentvolumeclaims/finalizers
              - pods/finalizers
              verbs:
              - update
            - apiGroups:
              - ""
              resources:
              - pods
              - services
              verbs:
              - get
              - list
              - watch
              - create
              - delete
            - apiGroups:
              - ""
              resources:
              - secrets
              verbs:
              - get
              - list
              - watch
              - create
            - apiGroups:
              - ""
              resources:
              - namespaces
              verbs:
              - get
              - list
            - apiGroups:
              - extensions
              resources:
              - ingresses
              verbs:
              - get
              - list
              - watch
            - apiGroups:
              - ""
              resources:
              - configmaps
              verbs:
              - get
              - list
              - watch
              - create
              - update
            - apiGroups:
              - storage.k8s.io
              resources:
              - storageclasses
              verbs:
              - get
              - list
            - apiGroups:
              - route.openshift.io
              resources:
              - routes
              verbs:
              - get
              - list
              - watch
            - apiGroups:
              - ""
              resources:
              - serviceaccounts
              - services
              verbs:
              - get
              - list
              - watch
              - create
              - update
              - delete
            - apiGroups:
              - batch
              resources:
              - jobs
              verbs:
              - get
              - list
              - watch
              - create
              - delete
            - apiGroups:
              - apps
              resources:
              - deployments
              - daemonsets
              verbs:
              - get
              - list
              - watch
              - create
              - delete
            - apiGroups:
              - rbac.authorization.k8s.io
              resources:
              - clusterroles
              - clusterrolebindings
              - roles
              - rolebindings
              verbs:
              - get
              - list
              - watch
              - create
              - delete
            - apiGroups:
              - apiextensions.k8s.io
              resources:
              - customresourcedefinitions
              verbs:
              - get
              - list
              - watch
              - create
              - delete
            - apiGroups:
              - security.openshift.io
              resources:
              - securitycontextconstraints
              verbs:
              - get
              - list
              - watch
            - apiGroups:
              - security.openshift.io
              resourceNames:
              - privileged
              resources:
              - securitycontextconstraints
              verbs:
              - get
              - patch
              - update

      deployments:
        - name: cluster-network-addons-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: cluster-network-addons-operator
            strategy: {}
            template:
              metadata:
                labels:
                  name: cluster-network-addons-operator
              spec:
                containers:
                - env:
                  - name: MULTUS_IMAGE
                    value: docker.io/nfvpe/multus:latest
                  - name: LINUX_BRIDGE_IMAGE
                    value: quay.io/kubevirt/cni-default-plugins
                  - name: SRIOV_DP_IMAGE
                    value: quay.io/booxter/sriov-device-plugin:latest
                  - name: SRIOV_CNI_IMAGE
                    value: docker.io/nfvpe/sriov-cni:latest
                  - name: SRIOV_ROOT_DEVICES
                  - name: KUBEMACPOOL_IMAGE
                    value: quay.io/schseba/mac-controller:latest
                  - name: OPERATOR_IMAGE
                    value: quay.io/kubevirt/cluster-network-addons-operator:latest
                  - name: OPERATOR_NAME
                    value: cluster-network-addons-operator
                  - name: POD_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.name
                  - name: WATCH_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  image: quay.io/kubevirt/cluster-network-addons-operator:latest
                  imagePullPolicy: Always
                  name: cluster-network-addons-operator
                  resources: {}
                serviceAccountName: cluster-network-addons-operator

  customresourcedefinitions:
    owned:
      - name: networkaddonsconfigs.networkaddonsoperator.network.kubevirt.io
        version: v1alpha1
        kind: NetworkAddonsConfig
        displayName: Cluster Network Addons
        description: Cluster Network Addons
