---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-network-addons-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cluster-network-addons-operator
  strategy: {}
  template:
    metadata:
      labels:
        name: cluster-network-addons-operator
    spec:
      containers:
      - env:
        - name: MULTUS_IMAGE
          value: docker.io/nfvpe/multus:latest
        - name: LINUX_BRIDGE_IMAGE
          value: quay.io/kubevirt/cni-default-plugins
        - name: SRIOV_DP_IMAGE
          value: quay.io/booxter/sriov-device-plugin:latest
        - name: SRIOV_CNI_IMAGE
          value: docker.io/nfvpe/sriov-cni:latest
        - name: SRIOV_ROOT_DEVICES
        - name: KUBEMACPOOL_IMAGE
          value: quay.io/schseba/mac-controller:latest
        - name: OPERATOR_IMAGE
          value: quay.io/kubevirt/cluster-network-addons-operator:latest
        - name: OPERATOR_NAME
          value: cluster-network-addons-operator
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/kubevirt/cluster-network-addons-operator:latest
        imagePullPolicy: Always
        name: cluster-network-addons-operator
        resources: {}
      serviceAccountName: cluster-network-addons-operator
